import { chromium } from "playwright";
const args = process.argv.slice(2);
const b = await chromium.launch({ channel: "msedge", args });
const p = await b.newPage();
const reqs = [];
p.on("request", r => reqs.push(r.url()));
p.on("requestfailed", r => console.log("  FAILED", r.url().slice(0,80), "->", r.failure()?.errorText));
await p.goto("http://82.25.109.251/", { waitUntil: "load", timeout: 45000 }).catch(e => console.log("  GOTO", e.message.split("\n")[0]));
await p.waitForTimeout(4000);
console.log("ARGS:", args.join(" ") || "(default)");
reqs.filter(u => u.includes("82.25")).slice(0, 8).forEach(u => console.log("  REQ", u.slice(0, 110)));
await b.close();