// ============================================================
// controllers/authController.js
// Registration, login, token refresh, logout, password reset,
// profile read/update, change password.
// ============================================================
import bcrypt from "bcryptjs";
import crypto from "crypto";
import User from "../models/User.js";
import Membership from "../models/Membership.js";
import ActivityLog from "../models/ActivityLog.js";
import asyncHandler from "../utils/asyncHandler.js";
import { notify } from "../services/notificationService.js";
import notificationService from "../notification/core/NotificationService.js";
import emailService from "../services/email/email.service.js";
import ApiError from "../utils/ApiError.js";
import {
  signAccessToken,
  signRefreshToken,
  verifyRefreshToken,
  signPurposeToken,
  verifyPurposeToken,
} from "../utils/token.js";
import { ensureReferral, applyReferral } from "../services/referralService.js";
import { buildStudentDashboard } from "../services/dashboardService.js";
import logger from "../notification/logger.js";

const MODULE = "AuthCtrl";
const FRONTEND_URL = process.env.FRONTEND_URL || "http://localhost:5173";
const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

const hashToken = (t) => crypto.createHash("sha256").update(t).digest("hex");

// Shape returned to the client on auth — matches what the React app stores.
// `memoStatus` can be passed from callers that already know the membership state.
function publicUser(user, memoStatus) {
  const planActive =
    memoStatus !== undefined ? memoStatus : (user.planMonths || 0) > 0;
  return {
    id: user._id,
    _id: user._id,
    name: user.name,
    email: user.email,
    role: user.role,
    status: user.status,
    phone: user.phone || "",
    city: user.city || "",
    style: user.style || "",
    level: user.level || "",
    planMonths: user.planMonths || 0,
    planActive,
    referralCount: user.referralCount || 0,
    months: user.months || 0,
    certifs: user.certifs || 0,
    stats: user.stats || { classes: 0, attendancePct: 0 },
    progress: user.progress || {
      flexibility: 0,
      strength: 0,
      breathing: 0,
      meditation: 0,
    },
    badges: user.badges || [],
    unreadNotifications: user.unreadNotifications || 0,
  };
}

async function issueTokens(user) {
  const accessToken = signAccessToken(user);
  const refreshToken = signRefreshToken(user);
  // Persist a hash of the refresh token so it can be revoked on logout.
  await User.findByIdAndUpdate(user._id, {
    $push: { refreshTokens: { $each: [hashToken(refreshToken)], $slice: -5 } },
  });
  return { accessToken, refreshToken };
}

// ── POST /api/auth/register ──────────────────────────────────
export const register = asyncHandler(async (req, res) => {
  const { name, email, password, phone, city, style, level, ref } = req.body;

  if (!name || !email) throw ApiError.badRequest("Name and email are required");
  if (!EMAIL_RE.test(email))
    throw ApiError.badRequest("Please provide a valid email address");

  const existing = await User.findOne({ email: email.toLowerCase().trim() });
  if (existing)
    throw ApiError.conflict("An account with this email already exists");

  // Allow admin-created students to omit a password (auto-generated + emailed).
  let raw = password;
  let autoGenerated = false;
  if (!raw || raw.trim() === "") {
    raw = crypto.randomBytes(5).toString("hex");
    autoGenerated = true;
  }
  if (!autoGenerated && raw.length < 6)
    throw ApiError.badRequest("Password must be at least 6 characters");

  const hashed = await bcrypt.hash(raw, await bcrypt.genSalt(12));

  const user = await User.create({
    name: name.trim(),
    email: email.toLowerCase().trim(),
    password: hashed,
    phone: phone || "",
    city: city || "",
    style: style || "Hatha",
    level: level || "Beginner",
  });

  // Every student gets a referral record; apply inbound referral credit.
  await ensureReferral(user);
  if (ref) await applyReferral(ref, user);

  // Welcome / credentials notification (dispatched via channel system).
  const welcomeMessage = autoGenerated
    ? `Hello ${name},<br><br>An administrator created your Pragya Yoga account.<br><strong>Email:</strong> ${user.email}<br><strong>Temporary Password:</strong> ${raw}<br><br>Please log in and change your password.`
    : `Hello ${name},<br><br>Welcome to Pragya Yoga! Your account is ready — sign in with the password you chose.`;

  notificationService
    .send(user._id, {
      template: "welcome",
      channels: ["inApp", "email"],
      data: {
        name: user.name,
        email: user.email,
        dashboardUrl: `${process.env.FRONTEND_URL || "https://pragyayoga.com"}/dashboard`,
        password: autoGenerated ? raw : undefined,
      },
      subject: autoGenerated
        ? "Your Pragya Yoga Account Credentials"
        : `Welcome to Pragya Yoga, ${user.name}!`,
      message: welcomeMessage,
      priority: "normal",
    })
    .catch((err) => {
      logger.error(MODULE, "Welcome email failed", {
        email: user.email,
        error: err.message,
        stack: err.stack,
      });
    });

  // Send welcome email via new email service (direct send)
  emailService.sendWelcome({
    email: user.email,
    name: user.name,
    dashboardUrl: `${process.env.FRONTEND_URL || "https://pragyayoga.com"}/dashboard`,
  }).catch((err) => logger.error(MODULE, "Welcome email via service failed", { error: err.message }));

  // Send admin notification about new registration
  emailService.sendRegistrationAdmin({
    studentName: user.name,
    email: user.email,
    phone: user.phone || '',
    registrationDate: new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' }),
  }).catch((err) => logger.error(MODULE, "Registration admin email failed", { error: err.message }));

  ActivityLog.create({
    action: "user_registered",
    targetUser: user._id,
    meta: { autoGenerated, email: user.email },
  }).catch(() => {});

  res.status(201).json({
    success: true,
    msg: autoGenerated
      ? "Student profile created. Temporary credentials emailed."
      : "Registration successful",
    autoGenerated,
    user: publicUser(user),
  });
});

// ── POST /api/auth/login ─────────────────────────────────────
export const login = asyncHandler(async (req, res) => {
  const { email, password } = req.body;
  if (!email || !password)
    throw ApiError.badRequest("Email and password are required");

  const user = await User.findOne({ email: email.toLowerCase().trim() });
  if (!user) throw ApiError.unauthorized("Invalid credentials");
  if (user.status === "banned")
    throw ApiError.forbidden("Your account has been suspended");

  const match = await bcrypt.compare(password, user.password);
  if (!match) throw ApiError.unauthorized("Invalid credentials");

  user.lastLogin = new Date();
  await user.save();

  const { accessToken, refreshToken } = await issueTokens(user);

  // Set refresh token as HttpOnly cookie (secure in production, same-site strict)
  res.cookie("refreshToken", refreshToken, {
    httpOnly: true,
    secure: process.env.NODE_ENV === "production",
    sameSite: "strict",
    maxAge: 30 * 24 * 60 * 60 * 1000, // 30 days
    path: "/api/auth",
  });

  // Fetch actual membership status — not just planMonths
  const membership = await Membership.findOne({ user: user._id }).sort({
    createdAt: -1,
  });

  ActivityLog.create({
    action: "user_login",
    performedBy: user._id,
    targetUser: user._id,
    meta: { email: user.email, role: user.role },
  }).catch(() => {});

  res.json({
    success: true,
    msg: "Login successful",
    token: accessToken,
    refreshToken,
    user: publicUser(user, membership ? (membership.isActive || membership.isPaused) : false),
  });
});

// ── POST /api/auth/refresh ───────────────────────────────────
export const refresh = asyncHandler(async (req, res) => {
  // Accept refresh token from body (legacy) or HttpOnly cookie (preferred)
  const refreshToken = req.body.refreshToken || req.cookies?.refreshToken;
  if (!refreshToken) throw ApiError.unauthorized("Refresh token required");

  let decoded;
  try {
    decoded = verifyRefreshToken(refreshToken);
  } catch {
    throw ApiError.unauthorized("Invalid or expired refresh token");
  }

  const user = await User.findById(decoded.id).select("+refreshTokens");
  if (!user || !user.refreshTokens.includes(hashToken(refreshToken))) {
    throw ApiError.unauthorized("Refresh token has been revoked");
  }

  const accessToken = signAccessToken(user);
  res.json({ success: true, token: accessToken });
});

// ── POST /api/auth/logout ────────────────────────────────────
export const logout = asyncHandler(async (req, res) => {
  const refreshToken = req.body.refreshToken || req.cookies?.refreshToken;
  let userId = null;
  if (refreshToken) {
    try {
      const decoded = verifyRefreshToken(refreshToken);
      userId = decoded.id;
      await User.findByIdAndUpdate(userId, {
        $pull: { refreshTokens: hashToken(refreshToken) },
      });
    } catch {
      /* token already invalid — nothing to revoke */
    }
  }
  // Clear the HttpOnly cookie
  res.clearCookie("refreshToken", { path: "/api/auth" });

  if (userId) {
    ActivityLog.create({
      action: "user_logout",
      performedBy: userId,
      targetUser: userId,
    }).catch(() => {});
  }

  res.json({ success: true, msg: "Logged out" });
});

// ── POST /api/auth/forgot-password ───────────────────────────
export const forgotPassword = asyncHandler(async (req, res) => {
  const { email } = req.body;
  console.log("🔥 FORGOT PASSWORD CONTROLLER HIT");
  if (!email) throw ApiError.badRequest("Email is required");

  logger.info(MODULE, "forgotPassword: request received", { email });

  const user = await User.findOne({ email: email.toLowerCase().trim() });
  if (user) {
    logger.info(MODULE, "forgotPassword: user found", {
      userId: String(user._id),
      userName: user.name,
      userEmail: user.email,
    });

    const token = signPurposeToken({ id: user._id, purpose: "reset" }, "15m");
    user.resetTokenHash = hashToken(token);
    user.resetTokenExpires = new Date(Date.now() + 15 * 60 * 1000);
    await user.save();

    const resetLink = `${FRONTEND_URL}/reset-password/${token}`;
    logger.info(MODULE, "forgotPassword: calling notificationService.send", {
      userId: String(user._id),
      userEmail: user.email,
      template: "password-reset",
      channels: ["inApp", "email"],
      resetLinkBase: `${FRONTEND_URL}/reset-password/`,
    });

    notificationService
      .send(user._id, {
        template: "password-reset",
        channels: ["inApp", "email"],
        data: {
          name: user.name,
          resetLink,
        },
        link: resetLink,
        priority: "high",
      })
      .then(() => {
        logger.info(
          MODULE,
          "forgotPassword: notificationService.send resolved",
          { userId: String(user._id) },
        );
      })
      .catch((err) => {
        logger.error(
          MODULE,
          "forgotPassword: notificationService.send rejected",
          {
            userId: String(user._id),
            error: err.message,
            stack: err.stack,
          },
        );
      });

    // Send password reset email directly via new email service
    emailService.sendResetPassword({
      email: user.email,
      name: user.name,
      resetLink,
    }).catch((err) => {
      logger.error(MODULE, "forgotPassword: emailService.sendResetPassword failed", {
        userId: String(user._id),
        error: err.message,
      });
    });
  } else {
    logger.warn(MODULE, "forgotPassword: no user found for email", { email });
  }

  res.json({
    success: true,
    msg: "If that email is registered, a reset link has been sent.",
  });
});

// ── POST /api/auth/reset-password/:token ─────────────────────
export const resetPassword = asyncHandler(async (req, res) => {
  const { token } = req.params;
  const { newPassword } = req.body;
  if (!newPassword || newPassword.length < 6)
    throw ApiError.badRequest("Password must be at least 6 characters");

  let decoded;
  try {
    decoded = verifyPurposeToken(token);
  } catch {
    throw ApiError.badRequest("Reset link is invalid or has expired");
  }
  if (decoded.purpose !== "reset")
    throw ApiError.badRequest("Invalid reset token");

  const user = await User.findById(decoded.id).select(
    "+resetTokenHash +resetTokenExpires",
  );
  if (
    !user ||
    user.resetTokenHash !== hashToken(token) ||
    !user.resetTokenExpires ||
    user.resetTokenExpires < new Date()
  ) {
    throw ApiError.badRequest("Reset link is invalid or has expired");
  }

  user.password = await bcrypt.hash(newPassword, await bcrypt.genSalt(12));
  user.resetTokenHash = null;
  user.resetTokenExpires = null;
  user.refreshTokens = []; // force re-login everywhere
  await user.save();

  res.json({
    success: true,
    msg: "Password reset successful. You can now sign in.",
  });
});

// ── GET /api/auth/profile ────────────────────────────────────
// Students receive the fully-aggregated dashboard object; admins
// receive their user record.
export const getProfile = asyncHandler(async (req, res) => {
  if (req.user.role === "admin") {
    return res.json(publicUser(req.user));
  }
  const dashboard = await buildStudentDashboard(req.user._id);
  if (!dashboard) throw ApiError.notFound("Profile not found");
  res.json(dashboard);
});

// ── PUT /api/auth/profile ────────────────────────────────────
export const updateProfile = asyncHandler(async (req, res) => {
  const { name, phone, city, style, level, bio, newPassword } = req.body;
  const updates = {};
  if (name !== undefined) updates.name = name.trim();
  if (phone !== undefined) updates.phone = phone;
  if (city !== undefined) updates.city = city;
  if (style !== undefined) updates.style = style;
  if (level !== undefined) updates.level = level;
  if (bio !== undefined) updates.bio = bio;
  // NB: email is intentionally immutable from the profile screen.

  if (newPassword && newPassword.trim() !== "") {
    if (newPassword.length < 6)
      throw ApiError.badRequest("Password must be at least 6 characters");
    updates.password = await bcrypt.hash(newPassword, await bcrypt.genSalt(12));
  }

  await User.findByIdAndUpdate(
    req.user._id,
    { $set: updates },
    { runValidators: true },
  );

  // Return the refreshed aggregated dashboard so the UI stays in sync.
  const dashboard = await buildStudentDashboard(req.user._id);
  res.json(dashboard);
});

// ── POST /api/auth/change-password ───────────────────────────
export const changePassword = asyncHandler(async (req, res) => {
  const { currentPassword, newPassword } = req.body;
  if (!currentPassword || !newPassword)
    throw ApiError.badRequest("Both current and new password are required");
  if (newPassword.length < 6)
    throw ApiError.badRequest("New password must be at least 6 characters");

  const user = await User.findById(req.user._id);
  const match = await bcrypt.compare(currentPassword, user.password);
  if (!match) throw ApiError.badRequest("Current password is incorrect");

  user.password = await bcrypt.hash(newPassword, await bcrypt.genSalt(12));
  await user.save();

  ActivityLog.create({
    action: "password_changed",
    performedBy: user._id,
    targetUser: user._id,
  }).catch(() => {});

  res.json({ success: true, msg: "Password changed successfully" });
});
